# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recording.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'recording.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frecording.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x01\n\x05\x45vent\x12 \n\ngame_start\x18\x01 \x01(\x0b\x32\n.GameStartH\x00\x12\"\n\x0b\x66rame_start\x18\x02 \x01(\x0b\x32\x0b.FrameStartH\x00\x12\x1c\n\x08game_end\x18\x03 \x01(\x0b\x32\x08.GameEndH\x00\x12&\n\rplayer_update\x18\x04 \x01(\x0b\x32\r.PlayerUpdateH\x00\x12.\n\x11projectile_update\x18\x05 \x01(\x0b\x32\x11.ProjectileUpdateH\x00\x42\x0c\n\nevent_type\"\"\n\nFrameStart\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\r\"R\n\tGameStart\x12.\n\nstart_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\x05stage\x18\x02 \x01(\x0e\x32\x06.Stage\"7\n\x07GameEnd\x12,\n\x08\x65nd_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa4\x01\n\x0cPlayerUpdate\x12\x17\n\x06player\x18\x01 \x01(\x0e\x32\x07.Player\x12\x12\n\nx_position\x18\x02 \x01(\x02\x12\x12\n\ny_position\x18\x03 \x01(\x02\x12\x12\n\nz_position\x18\x04 \x01(\x02\x12\x12\n\nx_velocity\x18\x05 \x01(\x02\x12\x12\n\ny_velocity\x18\x06 \x01(\x02\x12\x17\n\x0fnumber_of_jumps\x18\x07 \x01(\x05\"\x12\n\x10ProjectileUpdate*\xc1\x02\n\x05Stage\x12\x15\n\x11STAGE_UNSPECIFIED\x10\x00\x12\x17\n\x13STAGE_PEACHS_CASTLE\x10\x01\x12\x16\n\x12STAGE_CONGO_JUNGLE\x10\x02\x12\x17\n\x13STAGE_HYRULE_CASTLE\x10\x03\x12\x16\n\x12STAGE_PLANET_ZEBES\x10\x04\x12\x17\n\x13STAGE_YOSHIS_ISLAND\x10\x05\x12\x14\n\x10STAGE_DREAM_LAND\x10\x06\x12\x12\n\x0eSTAGE_SECTOR_Z\x10\x07\x12\x16\n\x12STAGE_SAFFRON_CITY\x10\x08\x12\x1a\n\x16STAGE_MUSHROOM_KINGDOM\x10\t\x12\x13\n\x0fSTAGE_DUEL_ZONE\x10\n\x12\x1b\n\x17STAGE_FINAL_DESTINATION\x10\x0b\x12\x16\n\x12STAGE_META_CRYSTAL\x10\x0c*c\n\x06Player\x12\x16\n\x12PLAYER_UNSPECIFIED\x10\x00\x12\x0e\n\nPLAYER_ONE\x10\x01\x12\x0e\n\nPLAYER_TWO\x10\x02\x12\x10\n\x0cPLAYER_THREE\x10\x03\x12\x0f\n\x0bPLAYER_FOUR\x10\x04\x62\x08\x65\x64itionsp\xe9\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recording_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STAGE']._serialized_start=629
  _globals['_STAGE']._serialized_end=950
  _globals['_PLAYER']._serialized_start=952
  _globals['_PLAYER']._serialized_end=1051
  _globals['_EVENT']._serialized_start=53
  _globals['_EVENT']._serialized_end=262
  _globals['_FRAMESTART']._serialized_start=264
  _globals['_FRAMESTART']._serialized_end=298
  _globals['_GAMESTART']._serialized_start=300
  _globals['_GAMESTART']._serialized_end=382
  _globals['_GAMEEND']._serialized_start=384
  _globals['_GAMEEND']._serialized_end=439
  _globals['_PLAYERUPDATE']._serialized_start=442
  _globals['_PLAYERUPDATE']._serialized_end=606
  _globals['_PROJECTILEUPDATE']._serialized_start=608
  _globals['_PROJECTILEUPDATE']._serialized_end=626
# @@protoc_insertion_point(module_scope)
